/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace de.dfki.tecs.robot.baxter
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MoveArmEvent : TBase
  {
    private Limb _limb;
    private Position _pos;
    private Orientation _ori;
    private Speed _speed;
    private Angles _angls;
    private Reference_sys _mode;
    private Kinematics _kin;

    /// <summary>
    /// 
    /// <seealso cref="Limb"/>
    /// </summary>
    public Limb Limb
    {
      get
      {
        return _limb;
      }
      set
      {
        __isset.limb = true;
        this._limb = value;
      }
    }

    public Position Pos
    {
      get
      {
        return _pos;
      }
      set
      {
        __isset.pos = true;
        this._pos = value;
      }
    }

    public Orientation Ori
    {
      get
      {
        return _ori;
      }
      set
      {
        __isset.ori = true;
        this._ori = value;
      }
    }

    public Speed Speed
    {
      get
      {
        return _speed;
      }
      set
      {
        __isset.speed = true;
        this._speed = value;
      }
    }

    public Angles Angls
    {
      get
      {
        return _angls;
      }
      set
      {
        __isset.angls = true;
        this._angls = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="Reference_sys"/>
    /// </summary>
    public Reference_sys Mode
    {
      get
      {
        return _mode;
      }
      set
      {
        __isset.mode = true;
        this._mode = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="Kinematics"/>
    /// </summary>
    public Kinematics Kin
    {
      get
      {
        return _kin;
      }
      set
      {
        __isset.kin = true;
        this._kin = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool limb;
      public bool pos;
      public bool ori;
      public bool speed;
      public bool angls;
      public bool mode;
      public bool kin;
    }

    public MoveArmEvent() {
      this._limb = (Limb)1;
      this._pos = new Position();
      this._ori = new Orientation();
      this._speed = new Speed();
      this._angls = new Angles();
      this._mode = (Reference_sys)0;
      this._kin = (Kinematics)0;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Limb = (Limb)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Pos = new Position();
              Pos.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Ori = new Orientation();
              Ori.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              Speed = new Speed();
              Speed.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Struct) {
              Angls = new Angles();
              Angls.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              Mode = (Reference_sys)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              Kin = (Kinematics)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MoveArmEvent");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.limb) {
        field.Name = "limb";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Limb);
        oprot.WriteFieldEnd();
      }
      if (Pos != null && __isset.pos) {
        field.Name = "pos";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Pos.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Ori != null && __isset.ori) {
        field.Name = "ori";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Ori.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Speed != null && __isset.speed) {
        field.Name = "speed";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        Speed.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Angls != null && __isset.angls) {
        field.Name = "angls";
        field.Type = TType.Struct;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        Angls.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.mode) {
        field.Name = "mode";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Mode);
        oprot.WriteFieldEnd();
      }
      if (__isset.kin) {
        field.Name = "kin";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Kin);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MoveArmEvent(");
      sb.Append("Limb: ");
      sb.Append(Limb);
      sb.Append(",Pos: ");
      sb.Append(Pos== null ? "<null>" : Pos.ToString());
      sb.Append(",Ori: ");
      sb.Append(Ori== null ? "<null>" : Ori.ToString());
      sb.Append(",Speed: ");
      sb.Append(Speed== null ? "<null>" : Speed.ToString());
      sb.Append(",Angls: ");
      sb.Append(Angls== null ? "<null>" : Angls.ToString());
      sb.Append(",Mode: ");
      sb.Append(Mode);
      sb.Append(",Kin: ");
      sb.Append(Kin);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
