/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace de.dfki.tecs.robot.baxter
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RetrieveApertureEvent : TBase
  {
    private string _right_aperture;
    private string _left_aperture;

    public string Right_aperture
    {
      get
      {
        return _right_aperture;
      }
      set
      {
        __isset.right_aperture = true;
        this._right_aperture = value;
      }
    }

    public string Left_aperture
    {
      get
      {
        return _left_aperture;
      }
      set
      {
        __isset.left_aperture = true;
        this._left_aperture = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool right_aperture;
      public bool left_aperture;
    }

    public RetrieveApertureEvent() {
      this._right_aperture = "100";
      this._left_aperture = "100";
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Right_aperture = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Left_aperture = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RetrieveApertureEvent");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Right_aperture != null && __isset.right_aperture) {
        field.Name = "right_aperture";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Right_aperture);
        oprot.WriteFieldEnd();
      }
      if (Left_aperture != null && __isset.left_aperture) {
        field.Name = "left_aperture";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Left_aperture);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RetrieveApertureEvent(");
      sb.Append("Right_aperture: ");
      sb.Append(Right_aperture);
      sb.Append(",Left_aperture: ");
      sb.Append(Left_aperture);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
