/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace de.dfki.tecs.robot.baxter
{
  public enum Kinematics
  {
    INVERSE = 0,
    FORWARD = 1,
  }
}
