/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.dfki.tecs.robot.baxter;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ImageType implements org.apache.thrift.TEnum {
  DFKI_LOGO(0),
  ACTION_TRIGGERED(1),
  SELECT_SURFACE(2),
  SYSTEM_READY(3),
  SYSTEM_SHUT_DOWN(4),
  PICK_ITEM(5),
  PICK_RESET(6);

  private final int value;

  private ImageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ImageType findByValue(int value) { 
    switch (value) {
      case 0:
        return DFKI_LOGO;
      case 1:
        return ACTION_TRIGGERED;
      case 2:
        return SELECT_SURFACE;
      case 3:
        return SYSTEM_READY;
      case 4:
        return SYSTEM_SHUT_DOWN;
      case 5:
        return PICK_ITEM;
      case 6:
        return PICK_RESET;
      default:
        return null;
    }
  }
}
