/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.dfki.tecs.robot.baxter;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Reference_sys implements org.apache.thrift.TEnum {
  ABSOLUTE(0),
  RELATIVE(1);

  private final int value;

  private Reference_sys(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Reference_sys findByValue(int value) { 
    switch (value) {
      case 0:
        return ABSOLUTE;
      case 1:
        return RELATIVE;
      default:
        return null;
    }
  }
}
