/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.dfki.tecs.robot.baxter;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Speed implements org.apache.thrift.TBase<Speed, Speed._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Speed");

  private static final org.apache.thrift.protocol.TField SPEED_LEFT_FIELD_DESC = new org.apache.thrift.protocol.TField("Speed_left", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SPEED_RIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("Speed_right", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SpeedStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SpeedTupleSchemeFactory());
  }

  public String Speed_left; // required
  public String Speed_right; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SPEED_LEFT((short)1, "Speed_left"),
    SPEED_RIGHT((short)2, "Speed_right");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SPEED_LEFT
          return SPEED_LEFT;
        case 2: // SPEED_RIGHT
          return SPEED_RIGHT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SPEED_LEFT, new org.apache.thrift.meta_data.FieldMetaData("Speed_left", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SPEED_RIGHT, new org.apache.thrift.meta_data.FieldMetaData("Speed_right", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Speed.class, metaDataMap);
  }

  public Speed() {
    this.Speed_left = "0.2";

    this.Speed_right = "0.2";

  }

  public Speed(
    String Speed_left,
    String Speed_right)
  {
    this();
    this.Speed_left = Speed_left;
    this.Speed_right = Speed_right;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Speed(Speed other) {
    if (other.isSetSpeed_left()) {
      this.Speed_left = other.Speed_left;
    }
    if (other.isSetSpeed_right()) {
      this.Speed_right = other.Speed_right;
    }
  }

  public Speed deepCopy() {
    return new Speed(this);
  }

  @Override
  public void clear() {
    this.Speed_left = "0.2";

    this.Speed_right = "0.2";

  }

  public String getSpeed_left() {
    return this.Speed_left;
  }

  public Speed setSpeed_left(String Speed_left) {
    this.Speed_left = Speed_left;
    return this;
  }

  public void unsetSpeed_left() {
    this.Speed_left = null;
  }

  /** Returns true if field Speed_left is set (has been assigned a value) and false otherwise */
  public boolean isSetSpeed_left() {
    return this.Speed_left != null;
  }

  public void setSpeed_leftIsSet(boolean value) {
    if (!value) {
      this.Speed_left = null;
    }
  }

  public String getSpeed_right() {
    return this.Speed_right;
  }

  public Speed setSpeed_right(String Speed_right) {
    this.Speed_right = Speed_right;
    return this;
  }

  public void unsetSpeed_right() {
    this.Speed_right = null;
  }

  /** Returns true if field Speed_right is set (has been assigned a value) and false otherwise */
  public boolean isSetSpeed_right() {
    return this.Speed_right != null;
  }

  public void setSpeed_rightIsSet(boolean value) {
    if (!value) {
      this.Speed_right = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SPEED_LEFT:
      if (value == null) {
        unsetSpeed_left();
      } else {
        setSpeed_left((String)value);
      }
      break;

    case SPEED_RIGHT:
      if (value == null) {
        unsetSpeed_right();
      } else {
        setSpeed_right((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SPEED_LEFT:
      return getSpeed_left();

    case SPEED_RIGHT:
      return getSpeed_right();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SPEED_LEFT:
      return isSetSpeed_left();
    case SPEED_RIGHT:
      return isSetSpeed_right();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Speed)
      return this.equals((Speed)that);
    return false;
  }

  public boolean equals(Speed that) {
    if (that == null)
      return false;

    boolean this_present_Speed_left = true && this.isSetSpeed_left();
    boolean that_present_Speed_left = true && that.isSetSpeed_left();
    if (this_present_Speed_left || that_present_Speed_left) {
      if (!(this_present_Speed_left && that_present_Speed_left))
        return false;
      if (!this.Speed_left.equals(that.Speed_left))
        return false;
    }

    boolean this_present_Speed_right = true && this.isSetSpeed_right();
    boolean that_present_Speed_right = true && that.isSetSpeed_right();
    if (this_present_Speed_right || that_present_Speed_right) {
      if (!(this_present_Speed_right && that_present_Speed_right))
        return false;
      if (!this.Speed_right.equals(that.Speed_right))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Speed other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Speed typedOther = (Speed)other;

    lastComparison = Boolean.valueOf(isSetSpeed_left()).compareTo(typedOther.isSetSpeed_left());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpeed_left()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Speed_left, typedOther.Speed_left);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSpeed_right()).compareTo(typedOther.isSetSpeed_right());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpeed_right()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Speed_right, typedOther.Speed_right);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Speed(");
    boolean first = true;

    sb.append("Speed_left:");
    if (this.Speed_left == null) {
      sb.append("null");
    } else {
      sb.append(this.Speed_left);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Speed_right:");
    if (this.Speed_right == null) {
      sb.append("null");
    } else {
      sb.append(this.Speed_right);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SpeedStandardSchemeFactory implements SchemeFactory {
    public SpeedStandardScheme getScheme() {
      return new SpeedStandardScheme();
    }
  }

  private static class SpeedStandardScheme extends StandardScheme<Speed> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Speed struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SPEED_LEFT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Speed_left = iprot.readString();
              struct.setSpeed_leftIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SPEED_RIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Speed_right = iprot.readString();
              struct.setSpeed_rightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Speed struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Speed_left != null) {
        oprot.writeFieldBegin(SPEED_LEFT_FIELD_DESC);
        oprot.writeString(struct.Speed_left);
        oprot.writeFieldEnd();
      }
      if (struct.Speed_right != null) {
        oprot.writeFieldBegin(SPEED_RIGHT_FIELD_DESC);
        oprot.writeString(struct.Speed_right);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SpeedTupleSchemeFactory implements SchemeFactory {
    public SpeedTupleScheme getScheme() {
      return new SpeedTupleScheme();
    }
  }

  private static class SpeedTupleScheme extends TupleScheme<Speed> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Speed struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSpeed_left()) {
        optionals.set(0);
      }
      if (struct.isSetSpeed_right()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSpeed_left()) {
        oprot.writeString(struct.Speed_left);
      }
      if (struct.isSetSpeed_right()) {
        oprot.writeString(struct.Speed_right);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Speed struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.Speed_left = iprot.readString();
        struct.setSpeed_leftIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Speed_right = iprot.readString();
        struct.setSpeed_rightIsSet(true);
      }
    }
  }

}

