/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace de.dfki.tecs.robot.baxter
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Speed : TBase
  {
    private string _Speed_left;
    private string _Speed_right;

    public string Speed_left
    {
      get
      {
        return _Speed_left;
      }
      set
      {
        __isset.Speed_left = true;
        this._Speed_left = value;
      }
    }

    public string Speed_right
    {
      get
      {
        return _Speed_right;
      }
      set
      {
        __isset.Speed_right = true;
        this._Speed_right = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Speed_left;
      public bool Speed_right;
    }

    public Speed() {
      this._Speed_left = "0.2";
      this._Speed_right = "0.2";
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Speed_left = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Speed_right = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Speed");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Speed_left != null && __isset.Speed_left) {
        field.Name = "Speed_left";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Speed_left);
        oprot.WriteFieldEnd();
      }
      if (Speed_right != null && __isset.Speed_right) {
        field.Name = "Speed_right";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Speed_right);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Speed(");
      sb.Append("Speed_left: ");
      sb.Append(Speed_left);
      sb.Append(",Speed_right: ");
      sb.Append(Speed_right);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
